# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tea, Code, and Anger
email: ian.bertolacci@gmail.com
description: Complaints about things I don't know enough about, and speculations about the horrors of becoming under-caffeinated.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ianbertolacci
github_username:  ian-bertolacci

# Build settings
markdown: kramdown
